# Generated by Django 2.0.3 on 2020-07-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', models.CharField(max_length=16)),
                ('expirationMonth', models.CharField(max_length=2)),
                ('expirationYear', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(blank=True, max_length=12, null=True)),
                ('amount', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('card_type', models.CharField(default='', max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='APIapp.Card')),
            ],
        ),
    ]
