# Generated by Django 2.0.3 on 2020-07-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_auto_20200712_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cc_number',
            field=models.CharField(max_length=100),
        ),
    ]
